/**
 * Browser-side Stellar address book.
 *
 * Stores named Stellar public keys in `localStorage`. Every entry is shape-
 * validated with Zod, and Stellar addresses are validated with
 * `StrKey.isValidEd25519PublicKey` before they are persisted.
 *
 * This module is safe to import from any environment — all `localStorage`
 * access is gated by an `isBrowser()` check so SSR / Node tooling won't
 * crash.
 */

import { z } from 'zod';
import { StrKey } from '@stellar/stellar-sdk';

const STORAGE_KEY = 'commitlabs:addressBook';
const LABEL_MAX_LEN = 50;

/** A single address book entry. */
export interface AddressBookEntry {
  /** Stable, locally-generated id. */
  id: string;
  /** Valid Stellar ed25519 public key (starts with 'G'). */
  address: string;
  /** Human-friendly label shown in the wallet menu (1–50 chars). */
  label: string;
  /** Unix ms timestamp at which the entry was created. */
  createdAt: number;
}

/** Zod schema used to validate every read/write path. */
const addressBookEntrySchema = z.object({
  id: z.string().min(1, 'id must be a non-empty string'),
  address: z
    .string()
    .refine((val) => StrKey.isValidEd25519PublicKey(val), {
      message: 'address must be a valid Stellar ed25519 public key (StrKey)',
    }),
  label: z
    .string()
    .min(1, 'label must be a non-empty string')
    .max(LABEL_MAX_LEN, `label must be at most ${LABEL_MAX_LEN} characters`),
  createdAt: z
    .number()
    .int()
    .nonnegative('createdAt must be a non-negative integer'),
});

/**
 * Inputs accepted by `addEntry`. `id` and `createdAt` are generated by the
 * function so callers cannot accidentally collide or back-date entries.
 */
export type AddressBookInput = Pick<AddressBookEntry, 'address' | 'label'>;

/** Patch fields accepted by `updateEntry`. */
export type AddressBookUpdate = Partial<
  Pick<AddressBookEntry, 'address' | 'label'>
>;

function isBrowser(): boolean {
  return (
    typeof globalThis !== 'undefined' &&
    typeof (globalThis as { localStorage?: Storage }).localStorage !== 'undefined'
  );
}

function readStorage(): AddressBookEntry[] {
  if (!isBrowser()) return [];
  const raw = window.localStorage.getItem(STORAGE_KEY);
  if (raw === null || raw === '') return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    // Corrupt JSON — drop it so the next write is clean. No data loss for
    // a brand-new entry.
    return [];
  }

  if (!Array.isArray(parsed)) return [];

  const valid: AddressBookEntry[] = [];
  for (const candidate of parsed) {
    const result = addressBookEntrySchema.safeParse(candidate);
    if (result.success) {
      valid.push(result.data);
    }
    // Silent skip for invalid entries: corrupted storage shouldn't crash the UI.
  }
  return valid;
}

function writeStorage(entries: AddressBookEntry[]): void {
  if (!isBrowser()) return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));
}

/**
 * Generates a short, locally-unique id. Not cryptographically secure — these
 * ids are never exposed to other origins or persisted server-side.
 */
function generateId(): string {
  const rand = Math.random().toString(36).slice(2, 11);
  const time = Date.now().toString(36);
  return `${time}-${rand}`;
}

/**
 * Returns all entries, sorted by `createdAt` descending (newest first).
 *
 * Invalid entries already in storage are silently filtered out.
 */
export function getAllEntries(): AddressBookEntry[] {
  return readStorage().sort((a, b) => b.createdAt - a.createdAt);
}

/** Returns the entry with the given id, or `undefined` if missing. */
export function getEntry(id: string): AddressBookEntry | undefined {
  return readStorage().find((entry) => entry.id === id);
}

/**
 * Adds a new entry after validating its shape and Stellar address.
 *
 * @throws Error if `address` is not a valid Stellar public key or `label`
 *         is empty / too long.
 */
export function addEntry(input: AddressBookInput): AddressBookEntry {
  const candidate = {
    id: generateId(),
    address: input.address,
    label: input.label,
    createdAt: Date.now(),
  };

  const result = addressBookEntrySchema.safeParse(candidate);
  if (!result.success) {
    throw new Error(formatZodError(result.error));
  }

  const entries = readStorage();
  entries.push(result.data);
  writeStorage(entries);
  return result.data;
}

/**
 * Patches an existing entry. Returns the updated entry, or `undefined` if
 * no entry with the given id exists.
 *
 * @throws Error if the patch would produce an invalid entry (bad address or
 *         label constraints violated).
 */
export function updateEntry(
  id: string,
  patch: AddressBookUpdate,
): AddressBookEntry | undefined {
  const entries = readStorage();
  const idx = entries.findIndex((entry) => entry.id === id);
  if (idx === -1) return undefined;

  const merged: AddressBookEntry = {
    ...entries[idx],
    ...(patch.address !== undefined ? { address: patch.address } : {}),
    ...(patch.label !== undefined ? { label: patch.label } : {}),
  };

  const result = addressBookEntrySchema.safeParse(merged);
  if (!result.success) {
    throw new Error(formatZodError(result.error));
  }

  entries[idx] = result.data;
  writeStorage(entries);
  return result.data;
}

/** Removes the entry with the given id. Returns `true` if anything was removed. */
export function removeEntry(id: string): boolean {
  const entries = readStorage();
  const filtered = entries.filter((entry) => entry.id !== id);
  if (filtered.length === entries.length) return false;
  writeStorage(filtered);
  return true;
}

/** Clears every entry from storage. Intended for tests / "reset wallet" flows. */
export function clearAllEntries(): void {
  if (!isBrowser()) return;
  window.localStorage.removeItem(STORAGE_KEY);
}

/** Test-only: gets the raw storage key (used by the test suite). */
export function __getStorageKey(): string {
  return STORAGE_KEY;
}

function formatZodError(error: z.ZodError): string {
  return error.issues
    .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
    .join('; ');
}