allowBuilds:
  '"': true
  ',': true
  '-': true
  '[': true
  ']': true
  b: true
  d: true
  e: true
  esbuild: set this to true or false
  i: true
  l: true
  n: true
  o: true
  r: true
  s: true
  u: true
  unrs-resolver: set this to true or false
  v: true
